# Site settings
title: APES - Advice for Problems in Environmental Statistics
email: info@biom.uni-freiburg.de
description: "Advice for Problems in Environmental Statistics"
baseurl: "/APES"
url: "http://biometry.github.io/APES"

# Build settings
markdown: kramdown
permalink: pretty
