# Site settings
title: APES - Advice for Problems in Environmental Statistics
email: info@biom.uni-freiburg.de
description: "Advice for Problems in Environmental Statistics"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
